In [127]:
import pandas as pd
import glob
import numpy as np

In [65]:
#Extracting household power consumption files

files_hp = glob.glob(r'./p1-power-weather/household_power_consumption/*.csv')
df_list = []
for file in files_hp:
    df = pd.read_csv(file, sep = ';', header = None)
    df_list.append(df)
    
df_hp = pd.concat(df_list, ignore_index = True)

/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3166: DtypeWarning: Columns (2,3,4,5,6,7) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [67]:
df_hp

,0,1,2,3,4,5,6,7,8
0,1/1/2010,00:00:00,1.790,0.236,240.650,7.400,0.000,0.000,18.0
1,1/1/2010,00:01:00,1.780,0.234,240.070,7.400,0.000,0.000,18.0
2,1/1/2010,00:02:00,1.780,0.234,240.150,7.400,0.000,0.000,19.0
3,1/1/2010,00:03:00,1.746,0.186,240.260,7.200,0.000,0.000,18.0
4,1/1/2010,00:04:00,1.686,0.102,240.120,7.000,0.000,0.000,18.0
...,...,...,...,...,...,...,...,...,...
2053258,31/12/2008,23:55:00,0.484,0.064,247.69,2.2,0,0,0.0
2053259,31/12/2008,23:56:00,0.482,0.064,247.35,2.2,0,0,0.0
2053260,31/12/2008,23:57:00,0.482,0.064,246.99,2.2,0,0,0.0
2053261,31/12/2008,23:58:00,0.48,0.064,246.52,2.2,0,0,0.0
2053262,31/12/2008,23:59:00,0.482,0.062,246.97,2.2,0,0,0.0

In [66]:
len(df_hp)

2053263

In [241]:
#Extracting weather files

files_w = glob.glob(r'./p1-power-weather/weather/*.csv')
files_w.remove(r'./p1-power-weather/weather/postesSynop.csv')
df_list = []
lengths = []
dict_types = dict()

for file in files_w:
    df2 = pd.read_csv(file, sep = ';', header = 0)
    df_list.append(df2)
    lengths.append(len(df2))
    
df_w = pd.concat(df_list, ignore_index = True)

In [242]:
df_w

,numer_sta,date,pmer,tend,cod_tend,dd,ff,t,td,u,...,nnuage2,ctype2,hnuage2,nnuage3,ctype3,hnuage3,nnuage4,ctype4,hnuage4,Unnamed: 59
0,7005,20080801000000,101070,10,3,170,4.100000,292.250000,291.450000,95,...,mq,mq,mq,mq,mq,mq,mq,mq,mq,NaN
1,7015,20080801000000,100980,-240,6,160,3.100000,292.650000,291.850000,95,...,mq,mq,mq,mq,mq,mq,mq,mq,mq,NaN
2,7020,20080801000000,101080,220,1,230,8.700000,289.950000,286.850000,82,...,mq,mq,mq,mq,mq,mq,mq,mq,mq,NaN
3,7027,20080801000000,101250,260,1,240,5.100000,289.850000,285.150000,74,...,mq,mq,mq,mq,mq,mq,mq,mq,mq,NaN
4,7037,20080801000000,101190,50,2,210,5.100000,291.250000,290.450000,95,...,mq,mq,mq,mq,mq,mq,mq,mq,mq,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
679201,81401,20080331210000,100950,mq,mq,mq,mq,300.650000,293.950000,67,...,mq,mq,mq,mq,mq,mq,mq,mq,mq,NaN
679202,81405,20080331210000,100930,mq,mq,20,4.600000,300.350000,294.650000,71,...,mq,mq,mq,mq,mq,mq,mq,mq,mq,NaN
679203,81408,20080331210000,100880,mq,mq,30,2.100000,298.850000,296.150000,85,...,mq,mq,mq,mq,mq,mq,mq,mq,mq,NaN
679204,81415,20080331210000,100830,mq,mq,mq,mq,300.750000,296.950000,80,...,mq,mq,mq,mq,mq,mq,mq,mq,mq,NaN
679205,89642,20080331210000,98720,210,3,140,11.800000,267.550000,261.250000,57,...,mq,mq,mq,mq,mq,mq,mq,mq,mq,NaN

In [237]:
#df_w = df_w.replace('mq', 'NaN')

In [243]:
# Transforming data to numeric type
types = [int, int]+[float for _ in range(58)]
for i in range(len(types)):
    df_w.iloc[:,i] = pd.to_numeric(df_w.iloc[:,i], errors = 'coerce')
    #df_w.iloc[:,i]=df_w.iloc[:,i].astype(types[i])

In [244]:
df_w.head()

,numer_sta,date,pmer,tend,cod_tend,dd,ff,t,td,u,...,nnuage2,ctype2,hnuage2,nnuage3,ctype3,hnuage3,nnuage4,ctype4,hnuage4,Unnamed: 59
0,7005,20080801000000,101070.0,10.0,3.0,170.0,4.1,292.25,291.45,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7015,20080801000000,100980.0,-240.0,6.0,160.0,3.1,292.65,291.85,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7020,20080801000000,101080.0,220.0,1.0,230.0,8.7,289.95,286.85,82.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7027,20080801000000,101250.0,260.0,1.0,240.0,5.1,289.85,285.15,74.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7037,20080801000000,101190.0,50.0,2.0,210.0,5.1,291.25,290.45,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [218]:
for el in df_w['dd']:
    if type(el)== str:
        print(el)
    break

In [245]:
df_w['dd'].mean()

177.99077274797284

In [252]:
# Extracting data corresponding to the right station
df_w=df_w[df_w["numer_sta"] == 7149]
df_w.iloc[1, 5]

250.0

In [253]:
df_w.dropna(axis = 1, thresh= 8000)

,numer_sta,date,pmer,tend,cod_tend,dd,ff,t,td,u,...,ssfrai,perssfrai,rr1,rr3,phenspe1,phenspe2,phenspe3,nnuage1,ctype1,hnuage1
9,7149,20080801000000,101220.0,50.0,0.0,230.0,4.1,294.05,291.25,84.0,...,0.0,-60.0,0.0,0.0,710.0,1107.0,3100.0,1.0,6.0,1200.0
67,7149,20080801030000,101460.0,220.0,1.0,250.0,7.2,290.85,287.95,83.0,...,0.0,-30.0,0.0,0.0,710.0,1112.0,3100.0,5.0,8.0,450.0
126,7149,20080801060000,101690.0,220.0,2.0,240.0,4.1,289.65,286.75,83.0,...,0.0,-60.0,0.0,0.0,710.0,1107.0,3100.0,1.0,8.0,450.0
185,7149,20080801090000,101800.0,120.0,1.0,240.0,5.1,292.05,286.05,68.0,...,0.0,-30.0,0.0,0.0,710.0,1109.0,3100.0,3.0,8.0,690.0
244,7149,20080801120000,101790.0,10.0,0.0,220.0,6.2,296.05,285.35,51.0,...,0.0,-60.0,0.0,0.0,710.0,1110.0,3100.0,3.0,8.0,1200.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
678922,7149,20080331090000,101460.0,130.0,3.0,180.0,4.1,280.85,279.15,89.0,...,0.0,-30.0,0.0,0.0,710.0,1107.0,3100.0,3.0,7.0,270.0
678978,7149,20080331120000,101640.0,190.0,1.0,230.0,3.1,283.15,279.85,80.0,...,0.0,-60.0,0.0,0.0,710.0,1106.0,3100.0,5.0,8.0,450.0
679035,7149,20080331150000,101740.0,110.0,3.0,0.0,0.0,286.35,279.65,64.0,...,0.0,-30.0,0.0,0.8,710.0,1103.0,3100.0,3.0,8.0,720.0
679095,7149,20080331180000,101970.0,220.0,3.0,250.0,2.1,284.75,278.65,66.0,...,0.0,-60.0,0.0,0.0,710.0,1106.0,3100.0,1.0,8.0,750.0
679155,7149,20080331210000,102220.0,230.0,1.0,240.0,2.1,279.55,277.35,86.0,...,0.0,-30.0,0.0,0.0,710.0,1105.0,3100.0,1.0,6.0,1800.0

In [212]:
def delete_cols(df, seuil):
    cols = []
    for col in df.columns:
        if len(df[df[col] == naan ]) > len(df)*seuil:
            cols.append(col)
    return df.drop(columns= cols)

In [235]:
naan = df_w.iloc[0, 12]

In [209]:
df_w.iloc[0, 12]

nan

In [210]:
type(df_w.iloc[0, 12])

numpy.float64

In [213]:
df_we = delete_cols(df_w, 0.3)

In [214]:
df_we

,numer_sta,date,pmer,tend,cod_tend,dd,ff,t,td,u,...,nnuage2,ctype2,hnuage2,nnuage3,ctype3,hnuage3,nnuage4,ctype4,hnuage4,Unnamed: 59
0,7005,20080801000000,101070.0,10.0,3.0,170.0,4.1,292.25,291.45,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7015,20080801000000,100980.0,-240.0,6.0,160.0,3.1,292.65,291.85,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7020,20080801000000,101080.0,220.0,1.0,230.0,8.7,289.95,286.85,82.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7027,20080801000000,101250.0,260.0,1.0,240.0,5.1,289.85,285.15,74.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7037,20080801000000,101190.0,50.0,2.0,210.0,5.1,291.25,290.45,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
679201,81401,20080331210000,100950.0,NaN,NaN,NaN,NaN,300.65,293.95,67.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
679202,81405,20080331210000,100930.0,NaN,NaN,20.0,4.6,300.35,294.65,71.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
679203,81408,20080331210000,100880.0,NaN,NaN,30.0,2.1,298.85,296.15,85.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
679204,81415,20080331210000,100830.0,NaN,NaN,NaN,NaN,300.75,296.95,80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
679205,89642,20080331210000,98720.0,210.0,3.0,140.0,11.8,267.55,261.25,57.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [133]:
df_we = df_we.replace('Nan', np.NaN)

SyntaxError: invalid syntax (<ipython-input-133-13d35ce92001>, line 1)

In [134]:
df_we["ff"].mean()

TypeError: Could not convert 4.1000007.2000004.1000005.1000006.2000005.1000005.1000003.1000002.1000003.1000003.1000005.1000007.2000006.2000007.2000003.1000002.1000005.1000004.1000005.1000005.1000005.1000006.2000007.2000005.1000006.2000004.1000005.1000005.1000005.1000005.1000005.1000001.0000000.0000002.1000003.1000003.1000004.1000004.1000002.1000002.1000000.0000002.1000003.1000002.1000004.1000004.1000000.0000003.1000003.1000006.2000006.2000005.1000003.1000004.1000002.1000005.1000004.1000005.1000006.2000007.2000006.2000005.1000004.1000001.0000003.1000001.0000005.1000005.1000006.2000005.1000005.1000004.1000004.1000005.1000004.1000005.1000005.1000007.2000005.1000003.1000003.1000001.0000002.1000003.1000004.1000003.1000004.1000003.1000005.1000006.2000008.2000009.8000009.8000009.8000007.2000006.2000006.2000008.2000009.8000008.7000008.2000008.2000003.1000003.1000002.1000003.1000003.1000004.1000003.1000002.1000002.1000001.0000001.0000002.1000003.1000003.1000005.1000003.1000001.0000001.0000002.1000002.1000004.1000005.1000004.1000004.1000002.1000002.1000002.1000004.1000005.1000007.2000006.2000003.1000002.1000002.1000003.1000004.1000007.2000006.2000006.2000008.2000004.1000005.1000005.1000004.1000006.2000008.7000009.8000005.1000005.1000003.1000004.1000003.1000006.2000007.2000005.1000003.1000002.1000002.1000003.1000001.0000004.1000005.1000005.1000003.1000002.1000001.0000000.0000001.0000002.1000003.1000004.1000004.1000003.1000003.1000003.1000003.1000003.1000006.2000005.1000003.1000001.0000001.0000001.0000002.1000003.1000004.1000003.1000003.1000002.1000002.1000001.0000002.1000003.1000003.1000003.1000004.1000003.1000003.1000002.1000001.0000001.0000003.1000002.1000004.1000002.1000001.0000002.1000001.0000001.0000003.1000004.1000003.1000004.1000002.1000003.1000001.0000002.1000002.1000003.1000003.1000003.1000002.1000001.0000002.1000002.1000003.1000004.1000005.1000002.1000003.1000002.1000003.1000002.1000004.1000004.1000002.1000001.0000001.0000001.0000005.1000001.0000005.1000006.2000005.1000003.1000004.1000003.1000002.1000003.1000005.1000005.1000004.1000002.1000004.1000003.1000003.1000004.1000008.2000008.2000008.2000003.1000002.1000003.1000004.1000003.1000005.1000005.1000005.1000005.1000004.1000003.1000004.1000005.1000006.2000005.1000004.1000003.1000003.1000002.1000002.1000004.1000005.1000006.2000008.7000008.7000008.7000005.1000006.2000007.2000007.2000008.2000005.1000008.2000007.2000007.2000005.1000007.2000007.2000008.2000003.1000003.1000002.1000001.0000003.1000003.1000003.1000003.1000002.1000001.0000001.0000000.0000000.0000003.1000005.1000003.6000004.1000002.1000001.0000002.1000001.0000003.6000004.1000005.1000002.1000001.0000000.0000000.0000000.0000004.1000002.1000005.7000007.2000003.6000004.6000002.6000003.1000004.1000004.1000005.1000003.6000002.6000001.0000002.6000002.6000003.6000005.1000005.1000005.7000005.7000004.6000004.1000004.6000004.6000003.6000004.6000004.6000003.6000003.1000001.0000001.5000002.6000005.1000003.6000004.1000003.6000002.1000001.5000002.1000003.1000005.1000005.7000004.1000003.6000002.1000002.6000003.6000006.2000007.7000006.7000005.7000004.6000004.6000003.1000003.6000003.1000002.1000001.5000002.1000001.5000001.0000001.5000002.6000004.1000004.1000006.2000004.6000003.1000003.6000003.6000002.6000004.1000006.2000006.2000005.1000003.6000004.1000004.1000005.7000005.7000007.7000007.7000004.6000004.6000003.6000003.6000004.1000005.1000004.6000005.7000004.1000005.1000005.7000003.6000003.6000003.6000003.1000004.6000004.1000001.5000002.1000001.0000000.0000001.0000002.6000003.6000004.6000003.6000002.6000003.1000002.6000005.1000005.1000005.1000006.7000006.2000004.6000004.6000003.6000005.7000008.2000007.7000005.1000004.6000004.1000002.1000004.1000005.1000007.2000005.7000003.6000001.5000001.0000002.1000000.5000001.5000002.1000002.1000001.0000001.0000002.1000001.0000002.1000001.5000003.6000005.1000002.6000002.6000002.1000005.1000004.6000005.1000005.7000005.7000006.7000006.2000004.1000002.1000002.1000002.1000003.1000001.0000002.1000002.1000001.0000001.0000001.0000000.0000002.1000003.1000003.1000004.1000006.2000006.2000007.2000007.2000007.2000008.7000006.2000006.2000004.1000004.1000005.1000006.2000006.2000005.1000001.0000001.0000001.0000003.1000003.1000002.1000004.1000004.1000002.1000002.1000001.0000001.0000001.0000001.0000002.1000003.1000003.1000003.1000003.1000004.1000004.1000005.1000003.1000004.1000003.1000001.0000002.1000004.1000006.2000008.2000009.8000008.7000004.1000005.1000002.1000001.0000001.0000001.0000002.1000007.2000002.1000002.1000003.1000003.1000005.1000005.1000006.2000008.2000005.1000004.1000006.2000008.2000006.2000008.2000009.8000008.2000003.1000005.1000004.1000006.2000007.2000008.70000010.80000012.9000008.7000008.7000007.2000008.7000003.1000006.2000006.2000005.1000003.1000004.1000004.1000004.1000005.1000005.1000005.1000009.8000008.2000005.1000003.1000003.1000001.0000001.0000006.2000005.1000002.1000005.1000003.1000001.0000003.1000002.1000004.1000003.1000003.1000004.1000003.1000000.0000000.0000005.1000003.1000005.1000002.1000001.0000000.0000002.1000001.0000002.1000001.0000001.0000002.1000002.1000001.0000001.0000002.1000001.0000004.1000004.1000002.1000001.0000000.0000001.0000001.0000002.1000002.1000004.1000001.0000002.1000002.1000002.1000003.1000003.1000006.2000007.2000002.1000002.1000003.1000002.1000003.1000003.1000004.1000006.2000005.1000003.1000003.1000004.1000003.1000005.1000005.1000006.2000005.1000006.2000005.1000005.1000006.2000008.7000008.7000007.2000005.1000006.2000007.2000009.8000006.2000007.2000006.2000006.2000002.1000005.1000005.1000005.1000004.1000006.2000007.2000007.2000004.1000003.1000004.1000004.1000002.1000003.1000008.2000006.2000006.2000006.2000005.1000004.1000007.2000008.7000009.8000007.2000008.7000008.7000008.20000010.8000008.7000004.1000008.2000008.7000003.1000003.1000003.1000003.1000003.1000003.1000005.1000005.1000005.1000006.2000008.7000008.2000008.2000009.8000009.8000006.2000003.1000002.1000000.0000003.1000002.1000004.1000006.2000004.1000004.1000004.1000007.2000007.2000006.2000008.2000006.2000007.2000008.2000007.2000008.2000009.8000008.7000008.2000009.8000007.2000008.2000006.2000005.1000005.1000005.1000004.1000004.1000001.0000001.0000004.1000004.1000001.0000002.1000003.1000003.1000005.1000003.1000002.1000002.1000002.1000002.1000004.1000005.1000008.2000007.2000003.1000003.1000003.1000003.1000001.0000003.1000003.1000003.1000002.1000001.0000002.1000000.0000000.0000001.0000002.1000003.1000001.0000001.0000000.0000001.0000001.0000001.0000002.1000002.1000003.1000001.0000001.0000001.0000003.1000004.1000003.1000004.1000003.1000003.1000002.1000003.1000004.1000005.1000004.1000004.1000003.1000002.1000001.0000002.1000002.1000001.0000003.1000002.1000002.1000000.0000003.1000003.1000001.0000004.1000003.1000002.1000003.1000003.1000003.1000005.1000005.1000005.1000004.1000004.1000005.1000005.1000008.2000008.2000007.2000007.2000007.2000006.2000006.2000006.2000006.2000005.1000006.2000006.2000006.2000006.2000004.1000003.1000004.1000006.2000007.2000005.1000007.2000008.7000006.2000006.2000005.1000006.2000006.2000008.2000007.2000005.1000004.1000005.1000005.1000008.2000004.1000005.1000004.1000004.1000005.1000003.1000004.1000005.1000004.1000003.1000005.1000006.2000006.2000006.2000003.1000006.2000007.2000006.2000004.1000004.1000004.1000002.1000002.1000006.2000005.1000005.1000004.1000003.1000003.1000002.1000003.1000002.1000003.1000004.1000003.1000002.1000001.0000002.1000001.0000001.0000000.0000003.1000003.1000000.0000000.0000000.0000001.0000002.1000002.1000004.1000006.2000003.1000001.0000001.0000002.1000005.1000004.1000004.1000002.1000002.1000003.1000003.1000001.0000001.0000002.1000002.1000005.1000002.1000002.1000002.1000000.0000002.1000002.1000004.1000003.1000002.1000009.8000007.2000008.7000009.8000008.7000005.1000003.1000007.2000009.8000006.2000004.1000007.2000008.2000007.2000006.2000004.1000004.1000004.1000002.1000003.1000004.1000005.1000006.2000006.2000007.2000007.2000005.1000005.1000007.2000005.1000005.1000003.1000004.1000003.1000004.1000005.1000007.2000006.2000004.1000007.2000006.2000003.1000006.2000005.1000007.2000006.2000007.2000007.2000004.1000003.1000003.1000004.1000005.1000006.2000004.1000006.2000007.2000007.2000006.2000007.2000007.2000007.2000006.2000005.1000005.1000005.1000005.1000007.2000007.2000007.2000005.1000005.1000005.1000005.1000004.1000004.1000005.1000007.2000004.1000002.1000003.1000003.1000006.2000007.2000009.8000008.2000009.8000006.2000005.1000002.1000002.1000004.1000006.2000005.1000005.1000005.1000005.1000003.1000003.1000003.1000005.1000006.2000004.1000005.1000004.1000005.1000003.1000002.1000002.1000001.0000001.0000000.0000000.0000000.0000000.0000001.0000003.1000002.1000004.1000004.1000003.1000001.0000003.1000003.1000004.1000003.1000004.1000004.1000004.1000005.1000006.2000007.2000008.7000008.7000008.2000008.2000009.8000008.7000009.80000011.80000013.90000011.8000009.8000006.2000008.7000008.2000007.2000007.2000006.2000005.1000004.1000005.1000006.2000006.2000005.1000008.2000009.8000007.2000002.1000003.1000004.1000008.2000008.2000007.2000007.2000006.2000003.1000003.1000003.1000001.0000002.1000002.1000001.0000003.1000004.1000007.2000008.7000009.80000010.80000010.80000010.80000010.8000009.8000008.2000006.2000005.1000004.1000004.1000003.1000004.1000003.1000003.1000003.1000008.2000006.2000006.2000008.2000006.2000006.2000005.1000003.1000002.1000002.1000001.0000003.1000003.1000003.1000003.1000003.1000002.1000004.1000002.1000003.1000003.1000001.0000002.1000002.1000003.1000002.1000003.1000004.1000005.1000003.1000004.1000003.1000003.1000002.1000001.0000002.1000003.1000001.0000002.1000001.0000002.1000003.1000004.1000004.1000003.1000003.1000003.1000002.1000001.0000001.0000001.0000001.0000003.1000002.1000002.1000001.0000002.1000003.1000005.1000004.1000006.2000004.1000004.1000004.1000003.1000003.1000003.1000004.1000004.1000005.1000005.1000004.1000003.1000006.2000007.2000008.2000007.2000008.7000007.2000008.7000006.2000008.70000010.80000010.8000009.8000007.2000006.2000005.1000005.1000003.1000004.1000006.2000006.2000005.1000004.1000003.1000003.1000003.1000002.1000004.1000004.1000005.1000003.1000005.1000002.1000004.1000005.1000006.2000007.2000008.2000007.2000005.1000006.2000005.1000006.2000005.1000004.1000004.1000001.0000001.0000001.0000001.0000002.1000002.1000001.0000003.1000001.0000000.0000001.0000002.1000002.1000002.1000003.1000004.1000004.1000003.1000003.1000002.1000003.1000006.2000006.2000005.1000003.1000003.1000002.1000001.0000003.1000002.1000003.1000003.1000001.0000002.1000002.1000003.1000002.1000002.1000003.1000002.1000003.1000003.1000002.1000002.1000003.1000003.1000002.1000001.0000001.0000002.1000001.0000001.0000001.0000001.0000002.1000003.1000003.1000003.1000004.1000002.1000004.1000006.2000005.1000005.1000005.1000005.1000005.1000005.1000006.2000006.2000006.2000006.2000007.2000004.1000004.1000003.1000004.1000005.1000005.1000005.1000003.1000001.0000001.0000002.1000002.1000002.1000003.1000003.1000003.1000004.1000003.1000003.1000005.1000006.2000006.2000005.1000006.2000003.1000003.1000003.1000002.1000003.1000003.1000004.1000003.1000001.0000001.0000000.0000001.0000002.1000001.0000002.1000001.0000001.0000000.0000000.0000002.1000004.1000001.0000004.1000002.1000001.0000001.0000001.0000002.1000003.1000003.1000001.0000001.0000001.0000002.1000004.1000001.0000003.1000002.1000007.2000006.2000005.1000005.1000004.1000003.1000002.1000002.1000000.0000001.0000003.1000004.1000003.1000002.1000003.1000002.1000002.1000002.1000003.1000000.0000001.0000002.1000002.1000002.1000002.1000001.0000001.0000000.0000001.0000003.1000005.1000005.1000001.0000006.2000001.0000002.1000002.1000004.1000003.1000006.2000005.1000005.1000002.1000001.0000001.0000003.1000003.1000003.1000002.1000001.0000000.0000001.0000000.0000001.0000002.1000003.1000002.1000001.0000001.0000000.0000000.0000002.1000003.1000003.1000000.0000001.0000002.1000004.1000002.1000003.1000004.1000005.1000004.1000001.0000001.0000004.1000004.1000007.2000006.2000006.2000005.1000006.2000003.1000003.1000003.1000003.1000004.1000004.1000003.1000002.1000001.0000002.1000001.0000003.1000002.1000000.0000002.1000002.1000001.0000002.1000001.0000002.1000004.1000005.1000003.1000002.1000003.1000002.1000002.1000003.1000002.1000003.1000004.1000004.1000002.1000005.1000001.0000000.0000003.1000005.1000003.1000004.1000003.1000002.1000004.1000003.1000004.1000004.1000003.1000001.0000000.0000001.0000001.0000003.1000002.1000003.1000004.1000002.1000002.1000003.1000004.1000004.1000003.1000003.1000002.1000002.1000002.1000002.1000003.1000003.1000002.1000003.1000002.1000001.0000000.0000000.0000002.1000003.1000006.2000006.2000003.1000001.0000001.0000001.0000000.0000003.1000005.1000006.2000003.1000002.1000002.1000003.1000004.1000005.1000008.2000006.2000003.1000002.1000002.1000002.1000002.1000003.1000005.1000004.1000002.1000004.1000002.1000002.1000003.1000001.0000003.1000005.1000003.1000003.1000003.1000004.1000005.1000005.1000005.1000004.1000004.1000003.1000002.1000001.0000002.1000001.0000003.1000004.1000002.1000001.0000001.0000002.1000004.1000005.1000004.1000002.1000005.1000003.1000004.1000003.1000004.1000006.2000005.1000006.2000006.2000004.1000004.1000004.1000005.1000006.2000006.2000008.2000005.1000005.1000004.1000004.1000004.1000006.2000006.2000005.1000005.1000004.1000003.1000003.1000004.1000004.1000004.1000002.1000002.1000001.0000000.0000001.0000000.0000001.0000002.1000003.1000001.0000000.0000001.0000002.1000001.0000002.1000005.1000004.1000003.1000003.1000003.1000004.1000005.1000005.1000005.1000004.1000006.2000005.1000003.1000002.1000003.1000005.1000005.1000003.1000003.1000002.1000003.1000003.1000002.1000003.1000004.1000003.1000002.1000001.0000001.0000001.0000001.0000001.0000003.1000004.1000003.1000004.1000002.1000003.1000004.1000002.1000002.1000004.1000003.1000003.1000002.1000002.1000002.1000003.1000004.1000004.1000004.1000004.1000004.1000003.1000003.1000005.1000005.1000005.1000006.2000004.1000003.1000002.1000002.1000002.1000004.1000001.0000002.1000002.1000004.1000003.1000003.1000004.1000006.2000005.1000003.1000002.1000003.1000003.1000004.1000005.1000005.1000004.1000004.1000004.1000004.1000005.1000004.1000003.1000004.1000004.1000006.2000008.2000005.1000008.2000005.1000006.2000008.2000008.2000003.1000004.1000005.1000004.1000003.1000007.2000008.2000007.2000006.2000005.1000007.2000006.2000007.2000006.2000008.7000006.2000004.1000003.1000003.1000003.1000003.1000003.1000003.1000004.1000002.1000002.1000001.0000002.1000003.1000005.1000005.1000005.1000004.1000004.1000003.1000004.1000006.2000005.1000005.1000005.1000005.1000004.1000002.1000003.1000005.1000008.2000007.2000004.1000004.1000004.1000003.1000002.1000002.1000004.1000003.1000003.1000002.1000002.1000002.1000002.1000001.0000001.0000003.1000003.1000002.1000001.0000000.0000003.1000004.1000003.1000006.2000006.2000005.1000006.2000004.1000004.1000003.1000004.1000004.1000003.1000004.1000004.1000003.1000002.1000004.1000002.1000002.1000003.1000003.1000004.1000007.2000004.1000004.1000004.1000005.1000003.1000002.1000002.1000003.1000003.1000002.1000002.1000004.1000003.1000002.1000002.1000002.1000002.1000003.1000005.1000008.2000008.2000005.1000006.2000004.1000003.1000003.1000005.1000002.1000003.1000001.0000005.1000005.1000003.1000003.1000005.1000005.1000003.1000001.0000003.1000002.1000002.1000002.1000005.1000004.1000002.1000002.1000002.1000002.1000001.0000000.0000000.0000002.1000001.0000001.0000000.0000001.0000001.0000001.0000001.0000002.1000002.1000003.1000004.1000004.1000004.1000004.1000004.1000005.1000005.1000005.1000002.1000003.1000002.1000002.1000004.1000006.2000006.2000006.2000005.1000004.1000004.1000004.1000004.1000006.2000006.2000005.1000005.1000004.1000004.1000004.1000005.1000005.1000003.1000003.1000001.0000000.0000000.0000001.0000002.1000003.1000006.2000005.1000005.1000004.1000005.1000006.2000007.2000007.2000005.1000004.1000006.2000006.2000008.2000005.1000006.2000005.1000005.1000005.1000003.1000003.1000002.1000005.1000004.1000005.1000002.1000004.1000004.1000005.1000005.1000008.2000007.2000008.7000008.2000007.2000004.1000002.1000006.2000006.2000008.7000006.2000005.1000006.2000008.2000008.2000007.2000008.2000007.2000005.1000006.2000004.1000004.1000004.1000004.1000006.2000008.2000006.2000008.2000008.20000010.8000007.2000008.2000008.2000006.2000006.2000007.2000007.2000006.2000006.2000005.1000007.2000008.2000004.1000003.1000001.0000001.0000001.0000007.2000009.80000011.8000008.2000003.1000006.2000008.2000007.2000008.7000007.2000005.1000007.2000006.2000004.1000004.1000005.1000005.1000008.2000006.2000005.1000005.1000004.1000004.1000005.1000006.2000007.2000006.2000003.1000004.1000004.1000006.2000006.2000006.2000004.1000004.1000002.1000001.0000002.1000002.1000005.1000004.1000005.1000003.1000003.1000006.2000004.1000001.0000002.1000001.0000003.1000001.0000004.1000006.2000004.1000004.1000004.1000005.1000006.2000004.1000003.1000002.1000004.1000004.1000004.1000002.1000004.1000003.1000001.0000002.1000002.1000004.1000003.1000003.1000003.1000006.2000005.1000004.1000004.1000005.1000003.1000004.1000004.1000005.1000003.1000003.1000004.1000004.1000004.1000002.1000002.1000003.1000003.1000002.1000002.1000002.1000003.1000002.1000003.1000001.0000003.1000001.0000002.1000003.1000002.1000004.1000003.1000006.2000006.2000006.2000004.1000004.1000005.1000004.1000006.2000007.2000005.1000004.1000004.1000003.1000001.0000006.2000003.1000005.1000007.2000006.2000005.1000004.1000005.1000006.2000006.2000004.1000002.1000000.0000002.1000004.1000007.2000006.2000005.1000005.1000004.1000002.1000000.0000002.1000004.1000004.1000004.1000003.1000002.1000000.5000001.0000001.5000002.6000003.6000005.1000003.6000003.1000004.1000006.2000003.1000003.6000004.6000003.1000002.1000001.5000003.1000002.1000002.6000001.5000001.0000001.5000002.1000001.5000000.5000001.0000001.5000003.1000003.6000002.6000002.6000001.5000002.1000001.0000001.0000002.6000001.0000002.6000003.1000002.1000001.5000000.0000000.0000002.6000003.6000002.6000001.5000007.2000003.6000003.6000003.6000004.6000003.1000004.6000004.6000003.6000004.1000003.6000003.1000002.6000002.6000002.6000003.1000002.1000003.6000002.1000003.1000003.6000005.1000003.6000004.6000005.1000003.6000002.1000000.5000002.1000004.1000006.7000004.6000004.1000004.1000002.6000003.1000003.6000002.6000003.6000003.6000003.1000001.5000001.5000002.1000002.1000003.1000003.6000005.1000004.1000003.1000002.1000002.1000003.1000003.6000005.1000005.1000004.1000002.1000002.1000002.1000003.6000003.1000001.5000001.5000000.0000001.5000000.0000001.0000001.5000003.1000003.1000002.6000003.1000002.1000002.1000002.6000002.6000001.5000002.6000004.6000003.1000002.6000004.1000005.1000002.1000002.1000003.6000005.7000003.1000001.5000000.0000001.0000001.5000001.5000001.0000001.5000001.0000000.5000000.0000000.0000001.5000002.6000003.6000002.6000001.5000001.0000001.0000004.1000005.1000006.2000005.1000003.1000005.1000003.1000002.1000002.6000002.1000003.6000004.1000003.6000002.6000003.1000003.1000002.1000003.6000002.1000003.1000001.5000003.6000002.1000000.5000001.0000003.1000004.1000003.6000003.1000002.6000000.0000001.0000000.5000002.6000005.1000003.1000002.1000000.5000001.0000003.1000001.5000002.1000004.1000002.1000003.6000001.0000002.6000001.5000002.1000004.1000006.2000005.1000004.1000002.1000001.5000001.0000001.5000004.1000004.1000006.7000004.1000002.1000003.1000005.1000004.6000007.7000007.2000006.7000007.2000004.6000004.1000003.6000003.6000005.1000003.6000004.6000003.1000003.6000002.6000001.0000001.0000002.1000003.6000002.6000002.6000001.5000001.0000000.0000001.0000002.6000004.1000004.6000003.6000002.1000002.1000002.1000003.1000004.1000007.2000007.2000006.2000005.1000005.1000004.1000005.1000006.2000006.2000009.8000007.2000004.1000005.1000004.1000004.1000003.1000006.2000006.2000003.1000005.1000005.1000004.1000007.2000008.2000009.8000006.2000004.1000005.1000005.1000008.2000007.2000007.2000008.2000008.2000006.2000007.2000005.1000004.1000005.1000007.2000008.2000008.2000006.2000002.1000002.1000001.0000002.1000002.1000003.1000003.1000002.1000002.1000003.1000002.1000003.1000003.1000002.1000006.2000004.1000002.1000002.1000001.0000003.100

In [125]:
def Fill_NA(df,col):
    mean = df[col].mean(skipna=True)
    df[col].fillna(value=mean)

In [121]:
for col in df_we.columns:
    Fill_NA(df_we,col)

TypeError: Could not convert 101220101460101690101800101790101740101730101840101870101840101820101760101690101630101560101740101790101780101760101730101550101390101130101100101040101020101240101400101430101430101420101640101710101700101760101770101660101550101460101470101540101490101400101360101220101000100850100850100740100610100500100790100890100800100630100740100710100830101000101130101240101390101540101730101780101790101770101770101670101510101360101330101250101130101080101090101030100950100880100940100950100890100850100820100600100390100300100160998109945099350996409981099950100060100390100500100590100770100920100960101090101190101440101570101620101680101690101550101450101380101500101460101470101560101700101660101610101590101630101530101360101310101190101020100880100820100890100870100800100830100980101000101000101000101120101140101070100990100960100890100830100830101030101120101100101100101120101070100980101060101260101380101440101520101650101680101730101710101790101770101790101800101870101760101710101680101720101650101460101400101400101290101340101440101660101720101650101650101700101660101590101550101620101550101450101470101460101490101470101430101530101540101520101680101810101850101880101970102110102170102230102340102470102440102370102360102440102450102430102430102490102400102300102210102360102340102270102290102310102260102190102150102190102160102110102110102150102080101920101820101900101820101710101650101590101430101260101180101230101170101090101230101220101300101240101290101550101590101680101810101870101840101700101670101650101570101420101230101080100870100670100720100970100980100950100870100850100830100780100760100870100800100740100750100820100700100640100590100650100580100390100230100080998509967099580997409986010002010027010042010047010047010051010068010069010066010078010095010109010115010127010143010149010158010169010180010173010160010156010161010160010149010139010128010125010128010134010150010159010165010172010182010167010149010141010141010129010111010103010092010085010072010102010109010120010126010138010151010153010147010157010171010174010174010184010189010177010177010183010189010195010199010206010218010215010212010222010231010232010230010233010235010224010220010223010234010228010226010230010234010218010207010212010217010215010212010216010214010199010184010192010199010200010199010202010204010202010200010207010218010218010221010235010249010252010254010266010277010280010281010290010293010281010266010264010267010264010251010246010240010220010213010212010220010220010212010217010218010202010191010193010201010204010202010205010206010196010186010189010191010186010183010192010208010214010214010230010248010256010260010268010284010279010277010287010299010304010308010314010322010307010300010310010314010313010306010307010305010285010269010270010275010269010267010266010268010253010237010233010235010227010213010206010204010194010183010191010201010194010180010165010156010144010124010109010106010277010280010289010302010303010302010309010315010314010316010314010323010324010322010334010345010352010358010359010371010358010344010345010342010336010323010310010304010278010251010241010240010229010208010194010191010176010159010156010146010131010110010091010083010066010044010041010035010029010013010000010000099970100050100160100100998709945098950991609938099460997709996010009010015010027010042010041010036010043010029010024010023010001010013010029010045010062010067010048010002099730100030999801002401003901002309998099590994109955099530995809987010019010058010081010108010138010137010138010129010108010081010042010012099920998509996010080010142010187010225010241010250010239010214010214010202010183010173010158010151010137010113010104010091010078010074010082010105010117010120010135010141010152010147010156010170010171010161010167010176010172010164010160010154010141010121010112010106010104010097010096010104010098010092010099010105010106010106010107010120010126010121010129010132010129010118010111010108010097010087010092010093010091010081010076010069010065010052010048010041010018099860998301000201002001002601003901003109992099680999109994099940100100100410100630100850101060101200101380101510101550101820102040102150102130102040101880101520101250101100100950100880100670100570100580100490100410100350100370100140997009968099860100010100070100190100300100460100680101020101190101150100940100630100170100040100220100460100910101260101440101700101910101960101910101860101720101420101010100760100600100980101180101620101860102050102070102000101900101690101360101180100990100840100600100540100430100370100320100350100330100300100320100610100980101330101610102000102290102450102530102720102920102940102920102860102850102750102770103100103450103660103800103960104110104040103830103830103860103800103670103640103610103410103140103080103040102910102750102690102690102590102430102490102610102630102680102780102970102960103090103270103380103400103450103540103490103340103350103360103280103140103080103040102910102720102700102810102890102860102920103070102970102800102820102900102860102710102700102800102790102650102530102430102180101780101490101210100940100720100640100410100070996409948099540995809966099980100210100320100350100400100550100580100560100840101020101110101180101310101340101420101380101520101670101680101660101710101730101730101590101620101670101600101470101410101240101140101000101120101240101250101330101380101380101230101140101190101230101220101180101280101470101540101620101730101810101750101640101640101650101620101530101590101680101680101610101580101550101380101240101280101410101390101380101460101520101450101340101440101510101510101430101450101540101450101280101250101220101060100970100920100980101050101050101170101380101460101490101600101720101720101760101870101920101960102010102040102240102450102320101920101660102090102540102670102760102730102760102990103180103310103460103400103390103250102940102710102370102060101780101590101700101770101840102060102230102360102410102440102440102410102400102400102370102330102270102170102150101970101760101710102000102160102280102280102300102120101850101690101380101090100800100660101020101090100890100840100980101170101260101410101590101690101720101880101940101910101820101710101750101660101820102320102570102780102720102510102310102150101920101930102240102560102860103010103040102990102890102880102870102840102800102800102720102580102350102340102390102500102830103150103410103400103280103350103290103270103170103040102980102770102550102490102440102410102350102280102290102180102010102010102000101970101920101840101780101600101460101440101350101090100880100740100710100600100580100990101350101390101510101790102150102400102450102550102480102340102100102010101950101850101870101920101910101870101740101770102000102010101910101930101920101840101680101580101530101430101370101420101470101430101400101300101190101030100840100980101050101040101050101010101050100970101000101150101290101440101630101900102200102330102380102560102650102680102650102670102700102770102610102640102750102800102900102970103210103340103360103550103630103690103610103520103460103310103110103070103000102910102840102780102800102740102670102690102720102700102640102590102680102660102550102570102630102550102450102530102580102570102550102640102790101950102020102100102260102180102160102230102340102400102360102410102400102220102030101970101990101880101850101850101900101820101710101730101830101840101790101750101770101700101650101740101960102040102080102150102230102180102060102050102220102260102220102280102340102240102120102120102270102330102310102400102480102400102350102430102590102590102520102540102530102410102230102180102220102210102150102140102130102060101920101920102060102140102160102240102320102280102160102210102390102430102350102390102360102190102030101960102030101970101910101960101930101850101740101760101870101810101720101720101780101640101640101670101760101820101820101940101980101860101820101870102020102030102040102130102130102020101950101980102110102150102130102150102170102090101980101990102110102170102070102140102200102140102110102180102340102430102460102530102580102450102320102290102380102340102280102220102150101980101790101750101860101910101920101990102020102000101900101860101990102060102080102100102100102020101930101920102040102140102110102140102180102120102000101990102110102140102130102180102170102120102000101950102020101990101930101950101950101840101640101530101540101470101410101370101370101280101180101280101500101510101510101520101580101530101470101510101650101750101770101880101920101880101740101740101900101980102000102070102070102030101880101830101910101900101840101800101740101570101380101410101340101280101190101130101110101010100900100840100970102050101970101950102010101970101910101920101960101940101900101880101940101850101770101820101830101810101760101760101820101750101710101810101880101880101970102070102140102150102150102210102310102340102200102240102280102150102040102050102080102060102000102020102080101950101890101990102060102080102060102100102120102060101960102060102160102180102190102280102380102430102450102580102680102740102700102690102770102620102420102230102160102170102130102110102260102300102310102540102650102660102690102760102880102770102610102640102660102640102560102590102630102580102540102580102640102600102520102520102590102500102370102330102350102270102210102160102150102010101870101890101900101870101800101770101820101820101820101910102010101980101960101910101960101850101710101730101750101690101670101660101790101930102100102360102570102700102830103020103230103280103250103350103460103490103410103410103500103430103320103360103400103390103360103440103560103500103400103450103490103440103310103280103230103030102810102820102730102600102450102410102510102490102330102410102400102370102260102240102290102120102070102150102210102190102110102150102190102060102040102130102200102220102130102100102150102050101950102030102020101990101910101940102040102060102140102310102540102590102750102860103020102980102880102930102910102800102660102570102560102350102190102080101980101810101570101460101390101210101170101310101590101770101860101930102110102180102260102500102720102790102840102980103100103060103040103150103230103260103250103280103330103320103280103300103410103390103350103320103440103390103270103280103290103250103140103060103110103020102910102910102890102840102770102770102890102780102740102850102900102940102920102920103010102950102800102880102830102780102840103060103230103310103280103420103460103450103230103140103040102840102740102720102720102680102510102400102380102130101910101790101600101810102020102210102470102610102710102880102920102860102680102490102410102330102250102330102250102130101990101850101860101790101740101850102020102150102260102380102540102540102460102530102560102490102360102210102050101700101320101080100920100900100910101020101390101580101710101900102110102200102270102350102580102620102580102740102860102900102890102970103040102990102960103060103120103090102970102970102940102790102580102530102370102130101830101630101370101000100630100330100150100130100150100280100510100620100620100680100710100670100590100460100390100370100280100190100130999801001401003101005401007101007001007201007501007101006501006301006701006101006001007301008501009601010301011701014801017101019301022101025201026901027201027701028301026801027001026901025001023601023601024901025601025401027201028601028901028801029701031501031801030801031501032201031601031401031201031401030301029201029501029201028101026601025601024601022401020201019601019001017101015801014401014601012801011701011101011901013601014501014801016001014901013401012601011001009901009401010101010601009401008401008001008901008901009101009401009401009101008901009601011301012001012201012601012801011601010401009901011501011401010401010501010501009501008501011201011101011701013401015301015801015701016501019001020201020201020801021301020601019501020201020601020401019501019001019401017801016701015301016501017001018201017301016601016901016901017501018101017901017701018601019501019801019401018201017901017001016001015501014901012501009301007101007101006201005901010301012301012801010901008901007901008601009401010601012101012401012001011001011101010301008401006701002909994010047010037010042010060010070010076010080010071010072010100010137010169010185010196010198010192010185010169010146010127010128010138010146010153010163010163010141010113010104010116010130010150010170010196010198010193010185010180010166010150010143010138010139010143010153010156010153010146010142010151010152010143010147010137010127010125010125010134010137010131010134010138010135010133010144010165010174010184010198010200010205010203010201010219010221010219010222010221010209010196010186010192010177010172010167010159010142010119010109010115010106010095010088010080010067010050010053010064010064010047010048010040010028010014010014010016010019010020010019010008099900996409952099620994909942099480996209988010013010040010073010085010098010110010122010121010125010127010134010134010117010108010101010101010096010101010107010111010115010119010121010111010093010104010120010163010148010137010123010107010087010080010088010099010100010121010142010150010154010154010168010166010167010171010174010174010171010170010188010193010194010203010204010195010185010180010189010190010188010193010189010181010171010170010179010177010179010176010174010161010150010148010164010176010168010183010191010196010193010196010208010209010206010206010207010199010190010183010188010186010183010179010177010168010158010153010168010167010169010175010175010171010161010166010184010193010193010201010212010218010216010214010226010231010231010237010230010213010197010186010195010199010190010189010186010182010175010177010191010192010189010196010194010186010175010170010178010175010173010172010167010154010143010133010153010164010165010174010170010163010152010145010161010160010159010166010173010172010165010169010195010203010207010206010208010198010184010175010184010187010184010181010182010169010155010149010160010155010143010142010148010151010179010174010210010221010218010237010237010229010218010220010232010238010238010243010247010236010222010221010228010222010213010206010196010170010142010128010124010109010097010090010086010080010073010073010089010089010092010107010118010128010132010137010149010150010155010157010162010153010142010137010149010158010163010170010175010169010156010146010155010154010156010164010182010184010180010185010206010211010220010234010242010238010226010224010234010236010232010234010236010221010206010196010200010196010184010179010170010139010109010088010087010113010101010097010094010091010081010078010086010085010080010085010091010091010087010096010105010099010083010073010048010021010019010032010056010075010087010095010105010109010126010134010155010160010158010167010178010184010179010175010157010143010129010145010154010160010162010169010181010179010183010186010192010195010188010185010191010196010192010188010182010171010167010165010176010174010169010166010165010152010152010157010172010169010159010156010151010146010139010142010153010161010159010164010172010170010172010174010185010191010191010196010196010188010189010184010194010190010184010179010172010149010131010120010121010121010127010141010154010154010146010135010141010138010118010115010117010101010094010093010102010103010111010123010120010117010122010124010147010164010173010181010188010182010174010173010188010192010193010204010207010200010194010188010195010191010184010179010179010165010149010139010141010128010124010115010130010151010155010170010185010186010182010179010173010163010152010143010155010151010147010151010150010140010124010104010095010065010034010015099960996609976099870100080100160100230100470100870101170101350101480101650101730101700101740101810101710101560101490101540101520101450101430101360101220101070101030101230101350101450101630101760101760101670101610101620101510101480101530101740101890101960101990102020101900101660101570101490101550101570101630101810101960102030102110102140102110102020102020102100102140102120102140102120102050101910101780101810102150102040102000101990101840101720101670101740101740101720101720101800101730101680101710101860101910101900101940102000101920101820101810101960101960101930101980102010101970101900101890102020101940101910101900101910101810101700101660101680101530101400101250101080100870100580100480100480100440100390100430100460100330100170100060100060999109979099870100070100250100570100790101010101160101250101440101650101730101830101970102170102250102270102370102400102310102160102100102150102070101980101990102000101860101760101740101800101820101870102010102170102250102240102410102670102800102840102870102920102870102790102720102750102680102590102560102500102310102110101980101950101740101620101700101720101610101420101410101510101460101500101500101390101240101270101400101500101480101570101710101700101660101760101960102010102020102030102090102030101910101960102080102060102040102090102100101950101790101770101830101780101780101800101840101730101650101670101840101880101900101940102000101910101850101870101990101970101960102000102020101860101710101670101650101580101450101340101200101030100810100790100810100580100310100260100390100380100460100580100740100790100940101070101270101320101350101420101510101450101330101240101160101080101000101020101040100920100960101040101170101270101330101420101530101570101560101640101770101850101870101940102020101990101930101920101980101880101780101780101760101720101650101630101690101640101520101590101590101450101460101560101610101590101550101490101630101680101680101690101700101650101690101680101760101810101840101920101900101780101670101600101630101540101320101210101150100990100890100800100840100840101010101200101330101380101450101490101680101740101780101880101920101840101830101820101880101860101830101840101810101720101640101700101840101860101880101940102070102000101910101840101940101930101870101810101800101650101530101480101540101610101570101620101600101500101430101380101550101530101450101500101530101480101390101320101460101510101510101550101670101650101660101710101850101880101840101840101820101750101760101740101800101800101760101760101700101570101480101430101500101500101490101530101560101630101600101550101630101590101480101480101500101560101590101620101670101650101580101590101610101570101420101310101230101140100990100990101050101060101120101160101360101460101530101620101650101600101520101500101650101680101720101840101940101900101880101930102140102220102260102370102410102310102160102030102110102070101830101740101670101570101310101170101110100890100680100550100550100580100510100530100740100910101020101240101420101530101560101650101810101840101830101770101780101730101550101410101340101320101240101230101170101050100820100690100590100640100540100550100600100610100650101110101540101780101950102080102180102170102110102130102220102190102130102050102020101900101670101630101690101860101950102020102140102170102180102240102410102490102480102520102580102470102340102220102220101200101310101490101630101720101850102020102160102270102290102330102390102370102240102190102340102260102220102210102150102080101980101990102040101990101950101990102050101960101890101880101980101930101880101890101840101730101620101570101690101610101550101570101530101430101350101390101560101550101500101490101510101440101410101400101480101480101510101610101700101730101710101700101800101830101830101870101890101760101660101540101610101640101590101570101580101510101370101370101440101450101360101410101450101420101370101370101420101410101360101440101460101420101270101190101220101150101120101060100990100870100690100600100670100570100460100430100400100370100200100190100240100260100340100490100540100440100490100570100710100760100760100800100850100740100680100730100830100880100870100870100820100650100610100420100550100770100860100940101010101050101080101090101260101250101180101210101090100870100650100550100910101090101300101510101570101560101440101350101400101360101340101460101510101400101400101320101390101270101140101010100960100930100940100870101020101